language: generic
services:
  - docker

before_install:
  - docker build -t ajblanco/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ajblanco/react-test npm test
after_success:
  - docker build -t ajblanco/multi-client ./client
  - docker build -t ajblanco/multi-nginx ./nginx
  - docker build -t ajblanco/multi-server ./server
  - docker build -t ajblanco/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajblanco/multi-client
  - docker push ajblanco/multi-nginx
  - docker push ajblanco/multi-server
  - docker push ajblanco/multi-worker
